# Generated by Django 5.1.5 on 2025-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_content_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="example_slug"),
            preserve_default=False,
        ),
    ]
